name: Build MPP Debian Package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build MPP package
        run: |
          mkdir -p mpp/build
          cd mpp/build
          cmake ..
          make package

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: mpp-deb-package
          path: mpp/build/*.deb
