name: Build MPP Package

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: my-mpp-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build package
        run: |
          apt update
          apt install -y build-essential cmake
          mkdir build && cd build
          cmake ..
          make package

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: mpp-package
          path: build/*.deb
